services:
  # Flask Web Service
  - type: web
    name: book-review-analyzer
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt && python train_and_save_model.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NLTK_DATA
        value: /opt/render/project/src/nltk_data
